// Generated by CoffeeScript 1.6.3
(function() {
  var app, async, express, http, server, yaq;

  express = require('express');

  http = require('http');

  yaq = require('./index');

  async = require('async');

  app = express();

  app.configure(function() {
    app.set('view engine', 'jade');
    app.set('views', __dirname + '/../views');
    app.use(function(req, res, next) {
      var m;
      if (m = req.url.match(/\/q\/([^\/]+)/)) {
        res.locals.q = yaq.create(m[1]);
      }
      return next();
    });
    return app.use(app.routes);
  });

  app.get("/q/:name/counts.json", function(req, res, next) {
    return res.locals.q.counts(function(err, counts) {
      if (err) {
        return next(err);
      }
      return res.json(counts);
    });
  });

  app.get("/q/:name", function(req, res) {
    var q;
    q = yaq.create(req.params.name);
    return res.render('queue', {
      q: q
    });
  });

  server = http.createServer(app);

  server.listen(5050);

}).call(this);
