// Generated by CoffeeScript 1.6.3
(function() {
  var Queue, queues;

  require('coffee-script');

  Queue = require('./queue');

  queues = {};

  module.exports.create = function(name, options) {
    if (options == null) {
      options = {};
    }
    return queues[name] || (queues[name] = new Queue(name, options));
  };

}).call(this);
